### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by BiohackUIO** [DIYbiosphere/sphere#314]
Biohack UIO - Community BioLab in the middle of the world
Hello DIYbiosphere community 👋

My name is Andrés Jarrín from Quito-Ecuador and I am the Co-Founder of Bioahck UIO

We’re excited to introduce **BioHack UIO**, the first community biotechnology lab in Ecuador 🇪🇨. We're thrilled to join this global ecosystem of open science, DIYbio, and citizen-driven innovation.

### 🌱 Who we are

**BioHack UIO** is an open and accessible biotech lab based in Quito, founded in 2019 to **democratize access to biotechnology**. We provide a space where students, professionals, educators, and curious minds can learn, experiment, and build with biotech tools—regardless of their background or financial means.

### 🧪 What we do

- Hands-on training in microbiology, molecular biology, bioinformatics, and synthetic biology  
- Open lab access and affordable memberships  
- Citizen science and bio-entrepreneurship projects  
- DIY lab equipment design (laminar flow hoods, spectrophotometers, incubators, etc.)  
- Community events, workshops, hackathons, and science festivals  

### 🌍 Our mission

To foster a **more inclusive, local, and regenerative biotechnology**. We believe everyone—not just institutions—should have the right to explore and apply science to real-world problems.

### 🤝 Why we’re joining DIYbiosphere

We admire this global network and fully align with its values. We’re eager to share our projects, collaborate with other nodes, contribute to open-source initiatives, and highlight biotech innovation emerging from the Global South.

### 📌 Key details

- 🌎 Country: Ecuador  
- 🧬 City: Quito  
- 🧪 Type: Community lab / hackerspace / makerspace  
- 🌐 Website: [biohackuio.com](https://www.biohackuio.com)  
- 📷 Instagram: [@biohack_uio]
- 🧵 Facebook: [@biohackuio](https://facebook.com/biohackuio)  
- 📧 Contact: ajarrin@biohackuio.com  

Thank you for welcoming us. We look forward to connecting and collaborating with all of you!

In open science and solidarity,  
— The **BioHack UIO** team

**Comment by danwchan** [comment]
Hmm I merged the branch but the Netlify failed and I I'm not 100% what how to troubleshoot or if I have access to fix.

@100ideas @jasonbobe can you give me access or otherwise resolve the error. What I can see from logs is that the netlify tried to initialize and install a "gem bundle" but this fails based on the rubygems version

3:18:30 PM: Using Ruby version 2.6.2
3:18:31 PM: Started restoring cached ruby gems
3:18:31 PM: Finished restoring cached ruby gems
3:18:31 PM: Installing gem bundle
3:18:33 PM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
3:18:33 PM: Fetching gem metadata from https://rubygems.org/..........
3:18:33 PM: Fetching gem metadata from https://rubygems.org/.
3:18:33 PM: Resolving dependencies...
3:18:33 PM: ffi-1.17.2-x86_64-linux-musl requires rubygems version >= 3.3.22, which is
3:18:33 PM: incompatible with the current version, 3.0.8
3:18:33 PM: Error during gem install
3:18:33 PM: Failing build: Failed to install dependencies

**Comment by BiohackUIO** [comment]
Hi Dan!
Thanks for getting back to me. I already filled out the template and submitted it as indicated in the repository instructions. However, I’ve noticed that the page for our lab (BioHack UIO) is still not appearing on the sphere.DIYbio.org website.

Could you please confirm if the pull request was received or if there’s any additional step I need to complete on my side?

Thanks again for your support—looking forward to being listed alongside other amazing community biolabs!

Best regards,
Andrés Jarrín
